name:  py build project

on:
  push:
    branches:
      - main
  workflow_dispatch:        
jobs:
  pybuildjob1:
    runs-on:  ubuntu-latest
    steps:
      - name: codecheckout 
        uses: actions/checkout@v4
      - name: pythoninstallation    
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
      - run: pytest   
