name:  py build project

on:
  push:
    branches:
      - main
  workflow_dispatch:        
jobs:
  pybuildjob1:
    runs-on: runner1 
    steps:
      - name: login as root user
        run: sudo su -
      - name: codecheckout 
        uses: actions/checkout@v4
      - name: pythoninstallation    
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - name: installing depndencies      
        run: pip install -r requirements.txt
      - name: executing test    
        run: pytest
        continue-on-error: true
      - name: check execution
        run: echo error ignored
      - name: Install docker
        uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
      - name: Build docker image    
        run: |
          set -x
          sudo docker version
          sudo docker build -t priya3103/pythondockerimg1 .
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 
      - name: docker push
        run: sudo docker push priya3103/pythondockerimg1      
